### PR TITLE
Configure option to disable installation of docs

### PR DESCRIPTION
**Pull request by OkoSanto**
I'd like an option to not install the documentation. This patch is what I'm currently using to do that, but my autotools experience is limited...

### CODE REVIEW

**Comment by svniemeijer** [comment]
Can you maybe explain why you want this option? Is it because you don't want to have the doxygen dependency?

**Comment by OkoSanto** [comment]
Mostly because I'd like to add CODA to the MXE cross compilation environment (see https://github.com/mxe/mxe/pull/1245). With MXE, you can compile libraries to 4 different targets (32 and 64 bits, static and shared), and documentation would be copied 4 times. I think their main concern is cluttering of the file system. (When cross-compiling, you are probably targeting end users who would not need most of that documentation anyway)

Avoiding the doxygen dependency is certainly another good motivation, though ;-)

**Comment by svniemeijer** [comment]
I think the better approach would be to use an opt-in approach to installation and only install what you want installed. automake generates a whole bunch of install-xxx subtargets that can be used to only install specific parts of the packages. For instance, install-exec will only install the executable parts, install-nodist_includeHEADERS will install the coda.h header file, etc.
From what I understood from your mxe patch you would be able to change the '$(MAKE) -C '$(1)' -j 1 install' to a (set of) different 'install-xxx' target(s).
If you need help in determining which install-xxx targets to use, then let me know what exactly you want to have installed.

**Comment by OkoSanto** [comment]
Yes, that does sound like a much better approach.

For my own purposes, I just need the libraries and the include files, but maybe for more general consumption, it's good to install the binary tools as well.

so 
```
$ make install-libLTLIBRARIES install-nodist_includeHEADERS install-exec
```
(install-exec seems to trigger install-libLTLIBRARIES, but perhaps it's good to be explicit)?

**Comment by svniemeijer** [comment]
If you want the binary tools, then you need install-binPROGRAMS as well

**Comment by svniemeijer** [comment]
So, either use install-exec or use install-libLTLIBRARIES and install-binPROGRAMS (but don't use both)

**Comment by svniemeijer** [comment]
Also, why do you call autoconf as part of the mxe script? This should not be needed if you use the source install package.
If you want to use your own versions of build tools, then it is maybe better to go all the way and use the git checkout (https://github.com/stcorp/coda/archive/2.15.1.tar.gz) and call the bootstrap script for that. You will then also need bison/flex/etc. though.

**Comment by OkoSanto** [comment]
(I called autoconf because I applied this patch to `configure.ac` and `
Makefile.am` as part of the MXE build. Now that I won't be using this patch anymore, this step is also obsolete.)

**Comment by svniemeijer** [comment]
Ok. Just be aware (for the future) that you will also need to call automake if you make changes to a Makefile.am. Better is to just call 'autoreconf -vif' (as is done in the bootstrap script) if you want to regenerate autotools files.

**Comment by svniemeijer** [comment]
Note that we will also remove the generate-finc from the next CODA release (coda.inc will become a static source file), so this should remove another problem.

**Comment by OkoSanto** [comment]
Thanks! And with that, let me close this flawed pull request...

**Pull request closed without merging**
